version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: trello-pro
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: postgress
    ports:
      - '5432:5432'
